-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cadastros
(
    coduser integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT unique_coduser UNIQUE (coduser)
);

CREATE TABLE IF NOT EXISTS public.logs
(
    id serial NOT NULL,
    acao text COLLATE pg_catalog."default" NOT NULL,
    coduser integer,
    nome text COLLATE pg_catalog."default",
    data_hora timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT logs_pkey PRIMARY KEY (id)
);
END;